[package]
name = "firmware"
version = "0.1.0"
authors = ["ktang <khttang@gmail.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.82"

[[bin]]
name = "firmware"
harness = false

[profile.release]
opt-level = "s"

[profile.dev]
debug = true 
opt-level = "z"

[dependencies]
anyhow = "1.0.103"
log = "0.4"
esp_idf_logger = "0.1.1"
embedded-svc = "0.29.0"

# Main toolchain modules
esp-idf-svc = { version = "0.52.1", features = ["critical-section", "embassy-time-driver", "embassy-sync"] }
esp-idf-sys = { version = "0.37.2", features = ["native"] } 

# FIX: Rename the crate locally to isolate it from esp-idf-svc's internal dependency links block
embassy-time = { package = "embassy-time", version = "0.5.1", features = ["generic-queue-8"] } 
edge-executor = "0.4"
async-channel = "2.3"
futures = "0.3"

serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
futures-util = "0.3.32"

[build-dependencies]
embuild = "0.33"

[package.metadata.esp-idf-sys]
sdkconfig_defaults = ["sdkconfig.defaults"]

[[package.metadata.esp-idf-sys.extra_components]]
component_dirs = ["esp32-camera"]
bindings_header = "bindings.h"
bindings_module = "camera"

[[package.metadata.esp-idf-sys.extra_components]]
component_dirs = ["c_components/sd_shim"]
bindings_header = "c_components/sd_shim/bindings.h"
bindings_module = "sd_shim"
